### ISSUE TITLE
Testing of token management contract

### ISSUE THREAD

**Issue by yourheropaul** [kowala-tech/kcoin#309]
We must prepare tests for token the management contract.

The tests should be automated, but if that's going to be very time consuming they can be manual. The tests must include at least:

- [x] Tokens must be transferrable between accounts. See #315 
- [x] It must be possible to get the balance of tokens for an account. See #307 
- [ ] New tokens must be mintable using the governance account(s). Required #311 

The tests should run as part of the CI testing pipeline.

(@rgeraldes I'm adding you here because you may need to advise on how the functionality works).
