### ISSUE TITLE
Launch zygote testnet

### ISSUE THREAD

**Issue by yourheropaul** [kowala-tech/kcoin#326]
Get this sucker online!

We'll need:

- [x] merged client code (#314)
- [x] an appropriate genesis.json (#312)
- [x] genesis.json should be packaged in `KUSD-testnet` release code
- [x] v5 boot nodes (#348)
- [x] a genesis validator
- [ ] tagged production release (#314)
- [x] redesigned netstats / basic docs page for Zygote (#325)
- [x] a faucet (#362 )
- [ ] restart network
