### ISSUE TITLE
Launch main net for token distribution

### ISSUE THREAD

**Issue by yourheropaul** [kowala-tech/kcoin#503]
This will require:

- [x] Bootnodes (should be in different regions)
- [x] Netstats (with new branding, see #501)
- [x] Explorer (new branding, see #501)
- [x] Genesis validator (needs keys, see #502)
- [ ] Archive nodes (in different regions)
- [ ] Up to date docs (see #310)
- [x] Update wallet-tools (needs live net details)
- [x] Need a secure key for the genesis validator (it's currently 53f)
- [x] Need a secure key for the multisig owner (it's current `17d`; see #646)
- [x] Make sure the governance keys are pre-funded
- [x] Default bootnodes and chain IDs for main net

Depends on: #502, #501, #310, #382 
Estimate: 4h

**Comment by acroca** [comment]
All services will run using `latest` docker tag.
